spring:
  data:
    mongodb:
      database: bibliopole
      host: localhost
      port: 27017
      #port: 0
      #database: test
  mongodb:
    embedded:
      version: 3.5.5
  output:
    ansi:
      enabled: always
  main:
    allow-circular-references: true
mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.skruglikov.bibliopole.db.migration