spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      database: bibliopole
      host: localhost
      port: 27017
  mongodb:
    embedded:
      version: 3.5.5
  output:
    ansi:
      enabled: always
mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.skruglikov.bibliopole.db.migration