spring:
  datasource:
    url: jdbc:h2:mem:bibliopole
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  output:
    ansi:
      enabled: always
  main:
    allow-circular-references: true