DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(
ID IDENTITY PRIMARY KEY,
NAME VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(
ID IDENTITY PRIMARY KEY,
FIRST_NAME VARCHAR(255) NOT NULL,
LAST_NAME VARCHAR(255) NOT NULL,
PATRONYMIC_NAME VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(
    ID IDENTITY PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    GENRE_ID BIGINT NOT NULL,
    AUTHOR_ID BIGINT NOT NULL,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID)
);

DROP TABLE IF EXISTS COMMENT;
CREATE TABLE COMMENT(
  ID IDENTITY PRIMARY KEY,
  TEXT VARCHAR(255),
  BOOK_ID BIGINT,
  CONSTRAINT fkCommentToBook FOREIGN KEY (BOOK_ID) references BOOK(id) ON DELETE CASCADE
);